# Generated by Django 3.2.20 on 2023-07-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fitnessplan',
            name='price',
        ),
    ]
