# Generated by Django 3.2.20 on 2023-07-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_auto_20230726_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
