# Generated by Django 3.2.20 on 2023-07-30 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_dayplan_is_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayplan',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_eight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayeight', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_eighteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayeighteen', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_eleven',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayeleven', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_fifteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayfifteen', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_fourteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayfourteen', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_nine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daynine', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_nineteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daynineteen', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_seventeen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayseventeen', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_sixteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daysixteen', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_ten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayten', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_thirteen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daythirteen', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_twelve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daytwelve', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_twenty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daytwenty', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_twentyeight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daytwentyeight', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_twentyfive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daytwentyfive', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_twentyfour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daytwentyfour', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_twentyone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daytwentyone', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_twentyseven',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daytwentyseven', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_twentysix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daytwentysix', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_twentythree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daytwentythree', to='plans.dayplan'),
        ),
        migrations.AddField(
            model_name='fitnessplan',
            name='day_twentytwo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daytwentytwo', to='plans.dayplan'),
        ),
    ]
