# Generated by Django 3.2.20 on 2023-08-02 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_auto_20230730_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
