# Generated by Django 3.2.20 on 2023-08-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_dayplan_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
    ]
