# Generated by Django 3.2.20 on 2023-07-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchandise', '0002_auto_20230629_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_plan',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
